image: maven:3.8.4-jdk-11

stages:
  - build
  - test
  - pitest

build:
  stage: build
  script:
    - ./mvnw clean compile

test:
  stage: test
  script:
    - ./mvnw clean test

pitest:
  stage: pitest
  script:
    - ./mvnw clean test org.pitest:pitest-maven:mutationCoverage
